### PR TITLE
Update build.properties

### PR DESCRIPTION
**Pull request by rex-remind101**
Was receiving `[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI` previously

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Thanks for creating this PR @rex-remind101. What is the exact error you are seeing (including the stacktrace)? Could it be that it is caused by the JDK you are using? https://github.com/sbt/sbt/issues/5093, https://github.com/sbt/sbt/issues/5509, https://stackoverflow.com/questions/60308229/scala-packages-cannot-be-represented-as-uri?

**Comment by rex-remind101** [comment]
I believe that was the case yes, after making this adjustment I no longer have that issue.

**Comment by tillrohrmann** [comment]
Thanks for confirming it. Closing this PR as a consequence. Thanks again for opening this PR @rex-remind101.

**Comment by rex-remind101** [comment]
Why close instead of merging, since this fixed the issue?

**Comment by tillrohrmann** [comment]
Sorry I might have misunderstood what you've said @rex-remind101. I thought that the problem is JDK related and not the sbt version, isn't it? Or differently asked, will the problem disappear with bumping the sbt version? If yes, how does it solve the problem?

**Comment by tillrohrmann** [comment]
On the other hand, bumping the sbt version shouldn't hurt in any case.

**Review by tillrohrmann — COMMENTED** [review]
LGTM. Merging this PR now.

**Comment by tillrohrmann** [comment]
Thanks for this contribution @rex-remind101!

**Pull request merged**
